version: '3.8'

services:
  # ---------------- Postgres ----------------
  postgres:
    image: postgres:15
    container_name: jani-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # ---------------- Redis ----------------
  redis:
    image: redis:7
    container_name: jani-redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  # ---------------- Auth Service ----------------
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    container_name: jani-auth
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${AUTH_PORT}
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  # ---------------- Next.js Frontend ----------------
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: jani-web
    working_dir: /app
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_AUTH_URL: ${NEXT_PUBLIC_AUTH_URL}
      PORT: ${WEB_PORT}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - auth
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
