import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "JANI",
  description: "Generated by H/OUADIA",
};

// Minimal root layout used temporarily for debugging prerender errors.
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased bg-white text-neutral-900">
        {children}
      </body>
    </html>
  );
}
