name: Branch Folder Check

on:
  push:
    branches: [auth, web, user, ai]
  pull_request:
    branches: [main]

jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure branch changes are only in allowed folder
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          case "$BRANCH" in
            auth) FOLDER="services/auth" ;;
            web) FOLDER="apps/web" ;;
            user) FOLDER="services/user" ;;
            ai) FOLDER="services/ai" ;;
            *) exit 0 ;;
          esac

          # List files changed in this push
          CHANGES=$(git diff --name-only origin/main...HEAD)
          OUTSIDE=$(echo "$CHANGES" | grep -v "^$FOLDER/")

          if [ -n "$OUTSIDE" ]; then
            echo "ERROR: Branch $BRANCH contains changes outside $FOLDER"
            echo "$OUTSIDE"
            exit 1
          fi
            echo "All changes are within the allowed folder: $FOLDER"