name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Setup pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 8

      # 4️⃣ Install dependencies at root
      - run: pnpm install --no-frozen-lockfile

      # 5️⃣ Build the Next.js frontend
      - run: pnpm --filter apps/web exec next build

      # 6️⃣ Build the Auth service
      - run: pnpm --filter services/auth exec tsc -p tsconfig.json
