name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout
      - uses: actions/checkout@v4

      # 2. Setup Node + pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          package-manager: 'pnpm'

      # 3. Install dependencies
      - run: pnpm install --frozen-lockfile

      # 4. Build all apps/services
      - run: pnpm -r run build
      # - run: pnpm -r run test
      # - run: pnpm -r run lint
      # - run: pnpm -r run typecheck